# Generated by Django 5.1.7 on 2025-03-19 18:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='blog_ID',
            new_name='blog_name',
        ),
    ]
